# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
#dir = "/home/user064/repo/backend_main/migrations"
dir = "/usr/src/app/migrations" # change it for working on docker\desktop pc